#!/bin/bash

# Activate primary screen 
xrandr --output LVDS1 --auto --mode 1600x900 --primary

# If we find that a screen is connected via VGA, activate it and position it
# to the left of the primary screen.
xrandr | grep 'VGA-*1 connected' | ifne xrandr --output VGA1 --auto --mode 1440x900  --right-of LVDS1

# If we find that a screen is connected via DVI, activate it and position it
# to the left of the primary screen.
xrandr | grep 'DP-*2 connected' | ifne xrandr --output LVDS1 --mode 1440x900
xrandr | grep 'DP-*2 connected' | ifne xrandr --output DP2 --mode 1440x900 --same-as LVDS1


#
# LOAD SCREEN BACKGROUNDS
#

# To set your backgrounds, run nitrogren /path/to/images
nitrogen --restore &


#
# STARTUP ICON TRAY
#

# We are using stalonetray to create a small icon tray at the
# top right of the screen. You are likely to want to tweak the
# size of the icons and the width of the tray based upon the
# size of your screen and your xmobar configuration. The goal is
# to make stalonetray look like it is part of xmobar.
# 
# Line by line, the options used by default below mean:
# - icons should be aligned with the "East" or right side of the tray
# - the width of the tray should be 5 icons wide by one icon tall, and it 
#   should be located 0 pixels from the right of the screen (-0) and 0 pixels
#   from the top of the screen (+0).
# - By setting our maximum geometry to the same thing, the tray will not grow.
# - The background color of the tray should be black.
# - This program should not show up in any taskbar.
# - Icons should be set to size "24".
# - Kludges argument of "force_icons_size" forces all icons to really, truly 
#   be the size we set.
# - window-strut "none" means windows are allowed to cover the tray. In
#   other words, trust xmonad to handle this part.
#
xrandr | grep 'DP-*2 connected' | ifne stalonetray \
  --icon-gravity E \
  --geometry 5x1-1440+0 \
  --max-geometry 5x1-1440+0 \
  --background '#000000' \
  --skip-taskbar \
  --icon-size 20 \
  --kludges force_icons_size \
  --window-strut none \
&

xrandr | grep -v 'DP-*2 connected' | ifne stalonetray \
  --icon-gravity E \
  --geometry 5x1-0+0 \
  --max-geometry 5x1-0+0 \
  --background '#000000' \
  --skip-taskbar \
  --icon-size 20 \
  --kludges force_icons_size \
  --window-strut none \
&

xinput --set-prop 11 "Synaptics Finger" 50 50 257
